// Generated by FsRouter

export interface GeneratedRoutes {
    "/users/:id": {
        params: {
            id: string;
        };
        "post": (c: Context<Env, "/:id", { params: { id: string; }; queries: {}; }>) => Response;
    };
    "/users": {
        params: {};
        "get": () => Response;
    };
}
