// Generated by FsRouter

export interface GeneratedRoutes {
    "/": {
        params: {};
        "get": (c: Context<Env, "/", { params: {}; queries: {}; }>) => Response;
    };
    "/users/:id": {
        params: {
            id: string;
        };
        "get": (c: Context<Env, "/users/:id", { params: { id: string; }; queries: {}; }>) => Response;
    };
    "/users": {
        params: {};
        "get": () => Response;
    };
}
